import { Modal, message, notification } from 'ant-design-vue';
import { toRem } from './common';
import dayjs from 'dayjs';
import * as config from '@/config';
export const $config = config;
export const $dayjs = dayjs;
export const $message = message;
export const $notification = notification;
export const $confirm = Modal.confirm;
export const $info = Modal.info;
export const $success = Modal.success;
export const $error = Modal.error;
export const $warning = Modal.warning;
export const $toRem = toRem;
