/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    BaseButton: typeof import('./../components/base-components/button/BaseButton.vue')['default']
    BaseDivider: typeof import('./../components/base-components/divider/BaseDivider.vue')['default']
    BaseLoading: typeof import('./../components/base-components/loading/BaseLoading.vue')['default']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepBackwardOutlined: typeof import('@ant-design/icons-vue')['StepBackwardOutlined']
    SvgIcon: typeof import('./../components/base-components/svg-icon/SvgIcon.vue')['default']
    TeamOutlined: typeof import('@ant-design/icons-vue')['TeamOutlined']
  }
}
