/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    BaseButton: typeof import('./../components/base-components/base-button/BaseButton.vue')['default']
    BaseDivider: typeof import('./../components/base-components/base-divider/BaseDivider.vue')['default']
    BaseLoading: typeof import('./../components/base-components/base-loading/BaseLoading.vue')['default']
    ProLayout: typeof import('./../components/base-components/pro-layout/ProLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
