/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    BaseButton: typeof import('./../components/base-components/base-button/BaseButton.vue')['default']
    BaseDivider: typeof import('./../components/base-components/base-divider/BaseDivider.vue')['default']
    BaseLoading: typeof import('./../components/base-components/base-loading/BaseLoading.vue')['default']
    Button: typeof import('.../components/base-components/base-divider/BaseDivider.vue'default']
    Divider: typeof import('../components/base-components/base-loading/BaseLoading.vue')['default']
    Loading: typeof import('./../components/base-components/base-loading/Loading.vue')['default']
    MvMap: typeof import('./../components/business-components/mv-map/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
